apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: serving-hpa
  namespace: mlops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serving-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics: []
